### ISSUE TITLE
Update deps for security reason

### ISSUE THREAD

**Issue by hirenchauhan2** [hirenchauhan2/JSONVue#1]
This repo has been there for so long and I have not been able to update it regularly. 
 Hence need to check if this extension works with a new version or any new changes are needed.

Ensure below:

- [ ]  Project is working fine after new changes

Happy Hactoberfest2020

**Comment by chinmay-chaudhari** [comment]
Hi @hirenchauhan2 ,

I am looking into this.

Can you please assign this to me?

Thanks.

**Comment by hirenchauhan2** [comment]
Hi, @chinmay9194 Assigned! 👍
